name: tabnewsnc_ui
description: "Cliente para visualizar e interagir com as not√≠cias/artigos publicados no TabNews"

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/TabNewsNC/tabnewsnc_ui

version: 0.1.1

environment:
  sdk: ^3.10.3
  flutter: ^3.38.4

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.3.2
  ionicons: ^0.2.2
  google_fonts: ^6.3.2
  tabnewsnc_engine:
    version: ^0.1.0
    git:
      tag_pattern: v{{version}}
      url: git@github.com:TabNewsNC/tabnewsnc_engine.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/animations/
